### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by jaspermayone** [MattIPv4/tweets-to-discord#1]
Any proper docs for setting this up?

**Comment by MattIPv4** [comment]
Been a while since I've set this up, but the gist should be:

- Get an approved Twitter application, so you have an API bearer token
- Grab your Twitter account ID
- Install the dependencies locally
- Authenticate wrangler with your Cloudflare account
- Set your Cloudflare account ID in wrangler.toml
- Create the required KV instance (TWEETS_TO_DISCORD_LAST_TWEET)
- Set the KV ids in wrangler.toml
- Configure the .env files based on the samples
- Deploy the worker with wrangler
